### ISSUE TITLE
set frequency?

### ISSUE THREAD

**Issue by jmikerq** [mikenz/Feather_M0_LoRa#2]
Hello, it's really nice of your clear instruction and code that makes it easy to test with the adafruit feather m0 lora boards.

Just a quick question in your code: I am not sure how you set the frequency of the end-node. Are they hidden somewhere or they are just pre-configurated to a certain frequency?

**Comment by mikenz** [comment]
My example is pre configured/hard coded for the KotahiNet frequencies here in New Zealand. You could hack it to work on other band plans.
