### ISSUE TITLE
Program will  not support Adafruit feather with Doorji(sx1278)LoRa module 

### ISSUE THREAD

**Issue by selvamaniraj** [mikenz/Feather_M0_LoRa#3]
Hi,
     I am trying to upload the program in Arduino Adafruit feather with Doorji(sx1278)LoRa module .it will upload but can't able to send the data to gateway. so i will check the Serial monitor only **starting...** only printed .How i can solve this issue . 

Thanks in advance.

**Comment by el8550** [comment]
Is your gateway LoRa or LoRaWAN?

**Comment by selvamaniraj** [comment]
HI,
         Thank you for your reply.And my gateway is LoRa.

**Comment by mikenz** [comment]
No clue sorry. This project is intended as an example for specific hardware on a specific lorawan network here in New Zealand.
