### ISSUE TITLE
Connection between io2 to pin 5 and io1 to 6

### ISSUE THREAD

**Issue by ELIVB** [mikenz/Feather_M0_LoRa#6]
Hello

I saw a connection between io2 to pin 5 and io1 to 6. Why these connections are used? 
Can i use other pins not 5 & 6?

Thank you very much for your kind help

ELI

**Comment by mikenz** [comment]
Yes, you can define alternative pins at https://github.com/mikenz/Feather_M0_LoRa/blob/master/Feather_M0_LoRa.ino#L57
